#!/usr/bin/env bash
# Local DarkStop dev stack: anvil + mock TEE/FTSO dependencies + DarkStopVault,
# wired into frontend/.env.local so `npm run dev` (in frontend/) talks to it.
#
#   scripts/dev-stack.sh          start anvil (if needed), deploy, write env
#   scripts/dev-stack.sh stop     stop the anvil this script started
#
# See frontend/README.md for the full local walkthrough (place order via UI,
# simulate the TEE settle with cast, watch the order flip to Executed).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RPC_URL="${DEV_STACK_RPC:-http://127.0.0.1:8545}"
# anvil's default funded account #0 — local development only.
DEV_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
ANVIL_PIDFILE="/tmp/darkstop-anvil.pid"
ANVIL_LOG="/tmp/darkstop-anvil.log"

export PATH="$HOME/.foundry/bin:$PATH"

if [[ "${1:-}" == "stop" ]]; then
  if [[ -f "$ANVIL_PIDFILE" ]] && kill "$(cat "$ANVIL_PIDFILE")" 2>/dev/null; then
    rm -f "$ANVIL_PIDFILE"
    echo "anvil stopped."
  else
    echo "no dev-stack anvil running (pidfile: $ANVIL_PIDFILE)."
  fi
  exit 0
fi

# 1. anvil ------------------------------------------------------------------
if cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1; then
  echo "==> reusing chain already listening at $RPC_URL"
else
  echo "==> starting anvil (log: $ANVIL_LOG)"
  nohup anvil --silent >"$ANVIL_LOG" 2>&1 &
  echo $! >"$ANVIL_PIDFILE"
  for _ in $(seq 1 50); do
    cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1 && break
    sleep 0.2
  done
  cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1 || {
    echo "anvil did not come up; see $ANVIL_LOG" >&2
    exit 1
  }
fi
CHAIN_ID="$(cast chain-id --rpc-url "$RPC_URL")"

# 2. deploy the stack --------------------------------------------------------
echo "==> deploying mocks + DarkStopVault (forge script contracts/dev/DevStack.s.sol)"
DEPLOY_OUT="$(cd "$ROOT" && forge script contracts/dev/DevStack.s.sol:DevStack \
  --rpc-url "$RPC_URL" --broadcast --private-key "$DEV_KEY" 2>&1)" || {
  echo "$DEPLOY_OUT" >&2
  exit 1
}

addr() { echo "$DEPLOY_OUT" | grep -o "${1}=0x[0-9a-fA-F]\{40\}" | tail -1 | cut -d= -f2; }
VAULT="$(addr ADDR_VAULT)"
USDT0="$(addr ADDR_USDT0)"
FTSO="$(addr ADDR_FTSO)"
[[ -n "$VAULT" && -n "$FTSO" ]] || {
  echo "could not parse deployed addresses from forge output:" >&2
  echo "$DEPLOY_OUT" >&2
  exit 1
}

# 3. frontend/.env.local -----------------------------------------------------
# No TEE extension runs in the local stack: the /api/tee-state proxy falls
# back to the repo's ECIES fixture pubkey (decryptable with the fixture
# private key — fine for local dev, never for a public network).
FIXTURE_PUBKEY="$(node -p \
  "JSON.parse(require('fs').readFileSync('$ROOT/internal/extension/testdata/ecies_vector.json','utf8')).publicKeyHex")"

cat >"$ROOT/frontend/.env.local" <<EOF
# Generated by scripts/dev-stack.sh — local anvil stack. Delete this file to
# fall back to the Coston2 defaults baked into frontend/lib/*.ts.
NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID
NEXT_PUBLIC_RPC_URL=$RPC_URL
NEXT_PUBLIC_EXPLORER_URL=
NEXT_PUBLIC_VAULT_ADDRESS=$VAULT
TEE_STATE_URL=http://localhost:7702/state
DEV_FALLBACK_TEE_PUBKEY=$FIXTURE_PUBKEY
# For cast commands (not read by Next.js):
# USDT0=$USDT0
# FTSO=$FTSO
EOF

echo
echo "==> dev stack ready (chain id $CHAIN_ID)"
echo "    Vault:  $VAULT"
echo "    USDT0:  $USDT0"
echo "    FTSO:   $FTSO"
echo "    env:    frontend/.env.local (written)"
echo
cat <<EOF
Next steps:
  1. cd frontend && npm run dev            # UI on http://localhost:3000
  2. MetaMask: add network (RPC $RPC_URL, chain id $CHAIN_ID) and import
     anvil key #0: $DEV_KEY
  3. Place an order in the UI (e.g. deposit 1, trigger 0.02).
  4. Simulate the price crossing + TEE settle (trigger 0.02 → 20000):
       export PATH="\$HOME/.foundry/bin:\$PATH"
       cast send $FTSO 'setFeed(uint256,int8,uint64)' 150000 7 \$(date +%s) \\
         --rpc-url $RPC_URL --private-key $DEV_KEY
       cast send $VAULT 'settle(uint256,uint256,uint256)' 1 20000 300 \\
         --rpc-url $RPC_URL --private-key $DEV_KEY
     The order flips Pending → Executed in the UI within a couple of seconds.
  5. scripts/dev-stack.sh stop             # tear down anvil
EOF
