#!/usr/bin/env bash
# Local DarkStop dev stack: anvil + mock TEE/FTSO dependencies + DarkStopVault,
# wired into frontend/.env.local so `npm run dev` (in frontend/) talks to it.
#
#   scripts/dev-stack.sh          start anvil (if needed), deploy, write env
#   scripts/dev-stack.sh stop     stop the anvil this script started
#
# See frontend/README.md for the full local walkthrough (encrypted relay into
# the Go extension, FTSO price drop, automatic watcher settlement).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RPC_URL="${DEV_STACK_RPC:-http://127.0.0.1:8545}"
# anvil's default funded account #0 — local development only.
DEV_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
ANVIL_PIDFILE="/tmp/darkstop-anvil.pid"
ANVIL_LOG="/tmp/darkstop-anvil.log"
EXTENSION_PIDFILE="/tmp/darkstop-extension.pid"
EXTENSION_LOG="/tmp/darkstop-extension.log"
EXTENSION_BIN="/tmp/darkstop-extension-demo"

export PATH="$HOME/.foundry/bin:$PATH"

if [[ "${1:-}" == "stop" ]]; then
  for item in "$EXTENSION_PIDFILE:extension" "$ANVIL_PIDFILE:anvil"; do
    pidfile="${item%%:*}"
    name="${item##*:}"
    if [[ -f "$pidfile" ]] && kill "$(cat "$pidfile")" 2>/dev/null; then
      rm -f "$pidfile"
      echo "$name stopped."
    else
      echo "no dev-stack $name running (pidfile: $pidfile)."
    fi
  done
  exit 0
fi

# 1. anvil ------------------------------------------------------------------
if cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1; then
  echo "==> reusing chain already listening at $RPC_URL"
else
  echo "==> starting anvil (log: $ANVIL_LOG)"
  nohup anvil --silent >"$ANVIL_LOG" 2>&1 &
  echo $! >"$ANVIL_PIDFILE"
  for _ in $(seq 1 50); do
    cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1 && break
    sleep 0.2
  done
  cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1 || {
    echo "anvil did not come up; see $ANVIL_LOG" >&2
    exit 1
  }
fi
CHAIN_ID="$(cast chain-id --rpc-url "$RPC_URL")"

# 2. deploy the stack --------------------------------------------------------
echo "==> deploying mocks + DarkStopVault (forge script contracts/dev/DevStack.s.sol)"
DEPLOY_OUT="$(cd "$ROOT" && forge script contracts/dev/DevStack.s.sol:DevStack \
  --rpc-url "$RPC_URL" --broadcast --private-key "$DEV_KEY" 2>&1)" || {
  echo "$DEPLOY_OUT" >&2
  exit 1
}

addr() { echo "$DEPLOY_OUT" | grep -o "${1}=0x[0-9a-fA-F]\{40\}" | tail -1 | cut -d= -f2; }
VAULT="$(addr ADDR_VAULT)"
USDT0="$(addr ADDR_USDT0)"
FTSO="$(addr ADDR_FTSO)"
[[ -n "$VAULT" && -n "$FTSO" ]] || {
  echo "could not parse deployed addresses from forge output:" >&2
  echo "$DEPLOY_OUT" >&2
  exit 1
}

# 3. real extension + watcher ------------------------------------------------
# The local relay uses the committed ECIES conformance fixture so the browser,
# Go extension and demo are deterministic. Production leaves this env unset.
FIXTURE_PUBKEY="$(node -p \
  "JSON.parse(require('fs').readFileSync('$ROOT/internal/extension/testdata/ecies_vector.json','utf8')).publicKeyHex")"
FIXTURE_PRIVKEY="$(node -p \
  "JSON.parse(require('fs').readFileSync('$ROOT/internal/extension/testdata/ecies_vector.json','utf8')).privateKeyHex")"

if [[ -f "$EXTENSION_PIDFILE" ]]; then
  kill "$(cat "$EXTENSION_PIDFILE")" 2>/dev/null || true
  rm -f "$EXTENSION_PIDFILE"
fi
echo "==> building + starting real Go extension/watcher (log: $EXTENSION_LOG)"
(cd "$ROOT" && go build -o "$EXTENSION_BIN" ./cmd)
nohup env \
  EXTENSION_PORT=7702 \
  CHAIN_URL="$RPC_URL" \
  VAULT_ADDRESS="$VAULT" \
  EXECUTOR_PRIVATE_KEY="$DEV_KEY" \
  ENCLAVE_PRIVATE_KEY="$FIXTURE_PRIVKEY" \
  "$EXTENSION_BIN" >"$EXTENSION_LOG" 2>&1 &
echo $! >"$EXTENSION_PIDFILE"

for _ in $(seq 1 50); do
  state_json="$(curl -fsS http://127.0.0.1:7702/state 2>/dev/null || true)"
  state_key="$(jq -r '.state.encryptionPubKey // empty' <<<"$state_json" 2>/dev/null || true)"
  trailing_ready="$(jq -r '.state.supportedPolicies | index("trailing") != null' <<<"$state_json" 2>/dev/null || true)"
  [[ "$state_key" == "$FIXTURE_PUBKEY" && "$trailing_ready" == "true" ]] && break
  sleep 0.2
done
[[ "${state_key:-}" == "$FIXTURE_PUBKEY" && "${trailing_ready:-}" == "true" ]] || {
  echo "extension did not start with the expected key and fresh trailing capability; see $EXTENSION_LOG" >&2
  exit 1
}

# 4. frontend/.env.local -----------------------------------------------------

cat >"$ROOT/frontend/.env.local" <<EOF
# Generated by scripts/dev-stack.sh — local anvil stack. Delete this file to
# fall back to the Coston2 defaults baked into frontend/lib/*.ts.
NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID
NEXT_PUBLIC_RPC_URL=$RPC_URL
NEXT_PUBLIC_EXPLORER_URL=
NEXT_PUBLIC_VAULT_ADDRESS=$VAULT
NEXT_PUBLIC_ORDERING_ENABLED=true
TEE_STATE_URL=http://127.0.0.1:7702/state
TEE_ACTION_URL=http://127.0.0.1:7702/action
DEV_FTSO_ADDRESS=$FTSO
# For cast commands (not read by Next.js):
# USDT0=$USDT0
# FTSO=$FTSO
EOF

echo
echo "==> dev stack ready (chain id $CHAIN_ID)"
echo "    Vault:  $VAULT"
echo "    USDT0:  $USDT0"
echo "    FTSO:   $FTSO"
echo "    env:    frontend/.env.local (written)"
echo
cat <<EOF
Next steps:
  1. cd frontend && npm run dev            # UI on http://localhost:3000
  2. MetaMask: add network (RPC $RPC_URL, chain id $CHAIN_ID) and import
     anvil key #0: $DEV_KEY
  3. Place + relay an encrypted order into the real Go extension:
       cd frontend && npx tsx scripts/place-order.ts && cd ..
  4. Drop only the price; the real Go watcher settles automatically:
       scripts/demo-settle.sh
     The order flips Pending → Executed in the UI within about five seconds.
  5. scripts/dev-stack.sh stop             # tear down anvil
EOF
